---
abstract: 'Add Attachments From Transactions'
author:
  - 'Christian Loos <cloos@netsandbox.de>'
build_requires:
  ExtUtils::MakeMaker: 6.59
configure_requires:
  ExtUtils::MakeMaker: 6.59
distribution_type: module
dynamic_config: 1
generated_by: 'Module::Install version 1.06'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: RT-Extension-AddAttachmentsFromTransactions
no_index:
  directory:
    - html
    - inc
    - t
  package:
    - RT::Action::SendEmail
    - RT::Attachment
    - RT::Ticket
requires:
  List::MoreUtils: 0
  perl: 5.8.3
resources:
  license: http://dev.perl.org/licenses/
  repository: https://github.com/cloos/RT-Extension-AddAttachmentsFromTransactions
version: 2.01
